### ISSUE TITLE
items context menus should open below themselves

### ISSUE THREAD

**Issue by A-Shahbazi** [lestcape/Appindicator#1]
currently when an item is clicked in appindicator applet the context menu opens at the middle of appindicator applet.
The desired behavior is that it opens under the item that is clicked.

**Comment by lestcape** [comment]
This applet is part of cinnamon right now: https://github.com/linuxmint/Cinnamon/commit/aed52793bed0b59c7763d1284cb6ea628c92f8fe

Wherever you considered a recommendation, is for all cinnamon devs, to be discussed, so then, your recommendation need to be in cinnamon web site. I provided a functional thing, to then be adapted to the user requirements, so thats clear, several things can be improved and adapted to be better.

Thats was always the idea of appindicator and is different to the idea of global menu where the last was developed to be part of an external applet.

Regards.

**Comment by A-Shahbazi** [comment]
I'm sorry I didn't know that.
I test latest cinnamon nightly and reported a bug here: linuxmint/Cinnamon/issues/4723

**Comment by lestcape** [comment]
Not matter, i appreciate you enforce, at last we work for the same things, a better desktop :). In fact, 2 of your issue was fixed by me, in the version inside cinnamon and another by @clefebvre.

Thanks.

**Comment by A-Shahbazi** [comment]
Yes I have noticed those.
I have closed them.

Thanks
